# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c977543d169c6f30690a99ef0edc31f67d4bb66a57a981ed1158c286ae150019c22b07180bdefd21b27bbf098617b713aa71f6cb3266d00e50a940c44cf090a

test:
  secret_key_base: 03a63fb5da50ac11225af556cf634fe4650fdf5402d6c94fe5c3ecef04f4c9f5dc3fb022aa3a2384d4a720fd1b21dec4e01448db0cef66ec91a648dae6ef30aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
